@url = http://localhost:5050/api

@accessToken = {{SignUp.response.body.accessToken}}

###
# @name SignUp
POST {{url}}/signup HTTP/1.1
content-type: application/json

{
    "name": "any_name",
    "email": "any_name@mail.com",
    "password": "any_password",
    "passwordConfirmation": "any_password"
}

###
# @name Login
POST {{url}}/login HTTP/1.1
content-type: application/json

{
    "email": "any_name@mail.com",
    "password": "any_password"
}

###
# @name AddSurvey
POST {{url}}/surveys HTTP/1.1
content-type: application/json
x-access-token: {{accessToken}}

{
    "question": "any_question",
    "answers": [
        {
            "image": "any_image",
            "answer": "any_answer"
        },
        {
            "answer": "other_answer"
        }
    ]
}

###
# @name LoadSurveys
GET {{url}}/surveys HTTP/1.1
x-access-token: {{accessToken}}
