version: "3"
services:
    mongo:
        container_name: mongo-container
        image: mongo:4.4.10
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    api:
        container_name: api-container
        restart: always
        build: .
        image: clean-node-api
        command: npm run debug
        ports:
            - "5050:5050"
            - "9222:9222"
        depends_on:
            - mongo
        links:
            - mongo
        environment:
          - MONGO_URL=mongodb://mongo:27017/clean-node-api?readPreference=primary&directConnection=true&ssl=false
